version: '3.7'

services:
    gonator:
        volumes:
         - ./:/app
        ports:
            - "8080:8080"

    caddy:
        volumes:
            - ./config/local.Caddyfile:/etc/caddy/Caddyfile
        ports:
            - "8081:8081"