version: '3.4'
services:
    gonator:
        build:
            context: "."
            dockerfile: "Dockerfile"
        ports:
            - "8080:8080"
        networks:
            - network1
    mongodb:
        container_name: mongodb4.4
        hostname: mongodb
        image: mongo:4.4.0
        volumes:
            - ./data/db:/data/db
            - ./scripts/mongoinit:/docker-entrypoint-initdb.d:ro
        networks:
            - network1
        healthcheck:
            test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
            interval: 10s
            start_period: 30s
        command: mongod --replSet "rs0"

networks:
   network1:
